"""add_has_used_free_limits_to_users

Revision ID: 615518dff6ec
Revises: e4d42188035b
Create Date: 2025-08-13 17:06:24.078712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615518dff6ec'
down_revision = 'e4d42188035b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_used_free_limits', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_used_free_limits')
    # ### end Alembic commands ###
