"""add_subscription_tokens_used_to_users

Revision ID: a2c9370e4ea9
Revises: f10dfeb9efc4
Create Date: 2025-08-13 14:47:34.334245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

revision = 'a2c9370e4ea9'
down_revision = 'f10dfeb9efc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)
    cols = [c['name'] for c in inspector.get_columns('users')]
    if 'subscription_tokens_used' not in cols:
        op.add_column('users', sa.Column('subscription_tokens_used', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tokens_used')
    # ### end Alembic commands ###
