"""add_free_limits_used_flag_to_users

Revision ID: e4d42188035b
Revises: a2c9370e4ea9
Create Date: 2025-08-13 17:04:35.124961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d42188035b'
down_revision = 'a2c9370e4ea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
