"""add_ai_credits_limit_to_subscriptions

Revision ID: f10dfeb9efc4
Revises: d8daca4de911
Create Date: 2025-08-13 14:30:23.537989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

revision = 'f10dfeb9efc4'
down_revision = 'd8daca4de911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)
    cols = [c['name'] for c in inspector.get_columns('subscriptions')]
    if 'ai_credits_limit' not in cols:
        op.add_column('subscriptions', sa.Column('ai_credits_limit', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'ai_credits_limit')
    # ### end Alembic commands ###
